title: Journal of Psychological Inquiry
description: A peer-reviewed journal showcasing undergraduate research in psychology.
baseurl: "/jpi"
url: "https://tomfaulkenberry.github.io"
markdown: kramdown
permalink: pretty

collections:
  issues:
    output: true
    permalink: /issues/:name/

defaults:
  - scope:
      path: ""
      type: "issues"
    values:
      layout: issue
  - scope:
      path: ""
    values:
      layout: page

plugins: []
